### ISSUE TITLE
Share Menu

### ISSUE THREAD

**Issue by thunsaker** [baieric/Xcerpt#7]
It would be great if I could share to Xcerpt, from my gallery app or wherever. It could save a step or two for many people.

Also, I'm interested in implementing this, if you're looking for help.

**Comment by baieric** [comment]
Thanks for the interest in Xcerpt! 😄 
I will implement this feature some time this month. I'll keep you updated!

Unfortunately I haven't gotten around to having a nice setup guide for how to use this repo yet, so it would be a pretty bad experience for you. You could still give it a try if you want, but there's ndk compiled stuff that will be hard to get set up without instructions.

**Comment by thunsaker** [comment]
I figured everything out. I actually had this up and running back in October, but ran out of time to contribute anything meaningful.

I submitted PR [#8](https://github.com/baieric/Xcerpt/pull/8) to handle this issue.

I had another suggestion for making it easier for yourself and others to develop: [Differentiate between the Debug/Release Builds](https://github.com/thunsaker/Xcerpt/pull/1)

I can also help get a setup guide going if you'd like.

**Comment by baieric** [comment]
Thanks for your PR! And yes, I am very open to any other contributions you would like to submit, like the debug/release builds and a setup guide.

**Comment by thunsaker** [comment]
Sweet, I'll keep them coming.
